.github/workflows/go.yml, .github/workflows/go21.yml, .github/workflows/go22.yml, .github/workflows/latestdepth.yml, .github/workflows/muzzle.yml, test/infra.go
run muzzle check and latestdepth test separately, and also add go1.22 test
=> try group test

pkg/rules/test/net_http_hook.go
=> fix: httpclient_test intermittent failure

.github/workflows/muzzle.yml, pkg/rules/goredis/goredis_data_type.go, pkg/rules/goredis/goredis_otel_instrumenter.go, pkg/rules/goredis/rule.go, pkg/rules/goredis/setup.go, rule_enabler.go, test/databasesql_tests.go, test/infra.go, test/integration_test.go, test/mongo_tests.go, test/redis/v9.0.5/go.mod, test/redis/v9.0.5/test_executing_commands.go, test/redis/v9.0.5/test_executing_unsupported_commands.go, test/redis/v9.0.5/test_redis_conn.go, test/redis/v9.0.5/test_redis_ring.go, test/redis/v9.0.5/test_redis_transactions.go, test/redis/v9.0.5/test_universal_client.go, test/redis_tests.go, test/test_main.go
=> feat: support redisv9

api/api.go, tool/instrument/template.go
=> feat: add CallContext.{GetKeyData,SetKeyData,HasKeyData} APIs

pkg/otel_setup.go
=> support grpc report

pkg/rules/mux/mux_data_type.go, pkg/rules/mux/mux_otel_instrumenter.go, pkg/rules/mux/mux_server_setup.go, pkg/rules/mux/rule.go, rule_enabler.go, test/build_test.go, test/databasesql_tests.go, test/errors_test.go, test/flags_test.go, test/gorm_tests.go, test/helloworld_test.go, test/httpclient_test.go, test/infra.go, test/integration_test.go, test/logrus_tests.go, test/mongo_tests.go, test/mux/v1.3.0/go.mod, test/mux/v1.3.0/test_mux_basic.go, test/mux/v1.3.0/test_mux_pattern.go, test/mux/v1.7.0/go.mod, test/mux/v1.7.0/test_mux_middleware.go, test/mux_tests.go, test/net_http_tests.go, test/redis_tests.go, test/test_main.go, test/zao_tests.go
=> support mux

tool/preprocess/dependency.go, tool/preprocess/preprocess.go
=> fix: dont preserve build cache after instrumentation

tool/instrument/inst_file.go, tool/instrument/inst_func.go, tool/preprocess/dependency.go, tool/preprocess/match.go, tool/preprocess/preprocess.go, tool/shared/ast.go
=> refine: faster compilation

tool/preprocess/preprocess.go, tool/util/util.go
more logs when compilation fails
=> refine: more logs when compilation fails

docs/how-to-inject-traceid-in-log.md, example/log/go.mod, example/log/main.go
=> add traceId example

tool/instrument/instrument.go, tool/preprocess/match.go, tool/shared/shared.go
=> refine: check consistency between preprocess and instrument

pkg/rules/test/rule.go, tool/instrument/trampoline.go, tool/preprocess/dependency.go, tool/preprocess/preprocess.go, tool/resource/bundle.go
fix for copying incorrect rule file dependencies
=> fix: copy incorrect rule file dependencies

tool/instrument/inst_func.go
=> fix: reroll when random suffix collision

test/helloworld_test.go, tool/shared/flags.go
-mod vendor is also a valid flag pattern
=> fix: aware of -mod vendor

tool/instrument/trampoline.go, tool/preprocess/dependency.go, tool/preprocess/match.go, tool/resource/bundle.go, tool/shared/shared.go, tool/util/util.go
=> fix: cannot match any rules on Windows

.github/workflows/go.yml, pkg/inst-api-semconv/instrumenter/http/http_metrics.go, pkg/verifier/access.go, pkg/verifier/runner.go, test/nethttp/test_http_metrics.go
=> add daily check for project

README.md, install.sh
=> feat: install via bash

.codeconv.yml, .github/workflows/go.yml, README.md
=> add coverage report

example/extension/sqlinject/demo/sql_inject.go
=> polish extension example

tool/instrument/inst_file.go, tool/instrument/instrument.go, tool/resource/bundle.go, tool/resource/ruledef.go
=> feat: easy debugging

docs/compatibility.md, test/helloworld_test.go, test/world/go.mod, test/world/main.go, test/world_test.go, tool/preprocess/match.go, tool/preprocess/preprocess.go, tool/shared/shared.go
match rules as much as possible and test if compilation works
=> refine: compile the world

pkg/inst-api/instrumenter/instrumenter_builder.go, pkg/inst-api/instrumenter/instrumenter_test.go, pkg/inst-api/utils/scope.go, pkg/inst-api/version/version.go, pkg/rules/databasesql/databasesql_otel_instrumenter.go, pkg/rules/fasthttp/fasthttp_otel_instrumenter.go, pkg/rules/goredis/goredis_otel_instrumenter.go, pkg/rules/goredisv8/goredis_v8_otel_instrumenter.go, pkg/rules/gorm/gorm_otel_instrumenter.go, pkg/rules/grpc/grpc_otel_instrumenter.go, pkg/rules/hertz/client/hertz_http_otel_instrumenter.go, pkg/rules/hertz/server/hertz_http_otel_instrumenter.go, pkg/rules/http/net_http_otel_instrumenter.go, pkg/rules/kratos/grpc/kratos_otel_instrumenter.go, pkg/rules/kratos/http/kratos_otel_instrumenter.go, pkg/rules/mongo/mongo_otel_instrumenter.go, pkg/rules/redigo/redigo_otel_instrumenter.go
=> support instrumentation scope

pkg/data/test_fmt.json, test/helloworld_test.go, tool/shared/shared.go
=> feat: optional max/min in version range

pkg/data/default.json, pkg/rules/logrus/setup.go
fix logrus for not use std logger
=> fix logrus

pkg/inst-api/instrumenter/span_suppressor.go, pkg/rules/elasticsearch/es_otel_instrumenter.go, pkg/rules/fiberv2/fiberv2_otel_instrumenter.go, pkg/rules/http/net_http_otel_instrumenter.go, pkg/rules/mongo/mongo_otel_instrumenter.go, test/elasticsearch/v8.4.0/test_es_metrics.go, test/elasticsearch/v8.5.0/test_es_typedclient_metrics.go, test/elasticsearch_tests.go, test/fiber_tests.go, test/fiberv2/v2.43.0/fiber_http_metrics.go, test/fiberv2/v2.43.0/go.mod, test/mongo/v1.11.1/test_metrics_mongo.go, test/mongo_tests.go, test/test_main.go, test/verifier/verifier.go
link issue (https://github.com/alibaba/opentelemetry-go-auto-instrumentation/issues/278)
=> ✨ add metrics for elasticsearch, fiberv2 and mongo

pkg/inst-api-semconv/instrumenter/http/http_status_code_extractor.go, pkg/inst-api-semconv/instrumenter/http/http_status_code_extractor_test.go
=> feat: modify the mapping of HTTP codes to OTel codes.

pkg/data/default.json, tool/preprocess/pkgdep.go, tool/preprocess/preprocess.go
some leftover imports should be rectified, this is a further fix for #291
=> fix: some leftover imports should be rectified

pkg/data/test_error.json, pkg/rules/test/error18/hook.go, test/errorstest/auxiliary/helper.go
add a test to check if param type of hook func could be type of func
=> test: add a test to check if param type of hook func could be type of func

tool/util/shared_test.go
I have tried to add some unit test cases based on the simple issues mentioned in the contribution explanation document. If there are any questions, please feel free to comment.
=> test: add unit tests to verify version comparison logic (#212) (#207)

pkg/otel_setup.go
=> support stdout, zipkin, none exporter

tool/instrument/inst_func.go, tool/instrument/inst_struct.go
add `//line` directive for struct
WIP Do not submit thanks.
=> feat: add //line directive for struct

docs/how-to-write-tests-for-plugins.md
=> polish how-to-write-tests-for-plugins.md

tool/instrument/inst_struct.go, tool/instrument/optimize.go, tool/instrument/trampoline.go
replenish return values of call context during optimization
=> fix: replenish return values of call context during optimization

pkg/dep/importer.go, tool/preprocess/preprocess.go
file has been changed unintentionally
=> fix: file has been changed unintentionally

Makefile
=> refine: trimming build path

go.mod, go.sum, test/build_test.go, tool/otel/main.go, tool/preprocess/preprocess.go, tool/util/shared.go
`otel go install` is available now
=> feat: otel go install

.github/workflows/trufflehog.yaml
Use https://github.com/trufflesecurity/trufflehog to avoid potential security risk.
=> add trufflehog scan for project

docs/how-to-add-a-new-rule.md
=> docs: Update how-to-add-a-new-rule.md

docs/how-to-write-tests-for-plugins.md, test/world_test.go
=> docs: Add explanation of world test in plugin test guide

pkg/inst-api-semconv/instrumenter/db/db_span_name_extractor_test.go, pkg/inst-api-semconv/instrumenter/message/message_attrs_extractor_test.go, pkg/rules/amqp091/README.md, pkg/rules/amqp091/README_CN.md, test/build_test.go, tool/instrument/inst_func.go, tool/preprocess/match.go, tool/preprocess/preprocess.go
=> chore: Fix typos

tool/config/config.go, tool/config/version.go, tool/data/exporter.go, tool/ex/wrap.go, tool/instrument/inst_file.go, tool/instrument/inst_func.go, tool/instrument/inst_struct.go, tool/instrument/instrument.go, tool/instrument/optimize.go, tool/instrument/trampoline.go, tool/otel/main.go, tool/preprocess/add.go, tool/preprocess/find.go, tool/preprocess/init.go, tool/preprocess/match.go, tool/preprocess/preprocess.go, tool/preprocess/sync.go, tool/preprocess/update.go, tool/rules/bundle.go, tool/rules/ruledef.go, tool/util/util.go
=> feat: simplify error handling chain

.github/workflows/basic.yml, .github/workflows/plugins1.yml
add github action manual trigger
=> ci: add github action manual trigger

.github/ISSUE_TEMPLATE/bug_report.yml, .gitignore, README.md, go.mod, test/sharedlib/go.mod, test/sharedlib/main.go, test/sharedlib/so/go.mod, test/sharedlib/so/plugin.go, test/sharedlib_test.go, tool/config/config.go, tool/instrument/inst_func.go, tool/instrument/instrument.go, tool/instrument/optimize.go, tool/instrument/trampoline.go, tool/preprocess/add.go, tool/preprocess/init.go, tool/preprocess/preprocess.go, tool/preprocess/update.go, tool/util/util.go
#554 
support permanent pkg module
=> feat: support permanent pkg module

.gitignore, example/nethttp/config.json, test/custom/rule.json, tool/ast/parser.go, tool/ast/primitives.go, tool/ast/shared.go, tool/instrument/inst_func.go, tool/instrument/trampoline.go, tool/preprocess/add.go, tool/preprocess/init.go, tool/preprocess/match.go, tool/preprocess/preprocess.go, tool/preprocess/update.go
support local path for custom rule
=> feat: support local path for custom rule

example/nethttp/rules/hook.go
Fix #581 
Need to handle exception responses.
=> fix: Fix the error in running nethttp test case
