alibaba/loongsuite-go-agent

api/api.go
pkg/rules/mongo/client_setup.go
pkg/rules/test/errors_hook.go
pkg/rules/test/fmt_hook.go
pkg/rules/test/long/sub/p4.go
pkg/rules/test/net_http_hook.go
pkg/rules/test/rule.go
test/errors-test/main.go
test/errors_test.go
tool/instrument/inst_func.go
tool/instrument/instrument.go
tool/instrument/optimize.go
tool/instrument/template.go
tool/instrument/trampoline.go
tool/preprocess/dependency.go
tool/shared/ast.go

Currently, if we want to change the parameters or return values of the original function, we are using a very error-prone and meticulously written code:
https://github.com/alibaba/opentelemetry-go-auto-instrumentation/blob/61d3c18d4fce92c394e83dfdb1952e140d8b4726/pkg/rules/test/fmt_hook.go#L19-L22
This troubles rule authors and is highly prone to errors. We should consider providing APIs in the CallContext to allow rule authors to easily modify parameters or return values without needing to understand the "pointer to a pointer is the original value" magic. For example:
```
call.SetParam(0, "olleH%s\n")
call.SetParam(1, "goodcatch")
call.SetReturnVal(0, 1024)
```
This patch significantly changes the form of the hook code; specifically, `CallContext` is no longer a struct but an interface. …

feat: new CallContext APIs

---

.gitignore
README.md
docs/compatibility.md
example/benchmark/benchmark.go
pkg/otel_setup.go
tool/preprocess/dependency.go
tool/shared/ast.go

Please review this patch to remove descrption about adding otel imports manually, that's painful for users.

fix: dont add otel imports manually

---

.gitignore
Makefile
README.md
docs/how-it-works.md
docs/how-to-add-a-new-rule.md
docs/how-to-debug.md
example/benchmark/README.md
pkg/otel_setup.go
test/infra.go
tool/shared/flags.go

chore: rename otel-go-auto-instrumentation to otelbuild

---

tool/preprocess/dependency.go

After applying this patch:
It's no longer the bottleneck.

refine: faster rule matching

---

tool/resource/bundle.go

It makes no sense to write file line by line, `json.Marshal/Unmarshal()` is all we need.

chore: load and store rule bundles directly

---

Makefile
README.md
test/databasesql_tests.go
test/helloworld_test.go
tool/preprocess/dependency.go
tool/preprocess/preprocess.go
tool/shared/flags.go
tool/shared/shared.go

No matter what build mode users use, we enforce the -mod=mod.

fix: enforce -mod=mod build mode

---

README.md
docs/anim-logo.svg
pkg/data/test_error.json
pkg/rules/test/error3/hook.go
tool/preprocess/pkgdep.go
tool/preprocess/preprocess.go
tool/preprocess/setup.go
tool/shared/ast.go

In hook code, if we import some package along with alias name and alias package is used within hook code, the compilation fails
```go
import (
erralias "errors"
"github.com/alibaba/opentelemetry-go-auto-instrumentation/pkg/api"
)
func onEnterErrorsNewAlias(call api.CallContext, text string) {
// Check if alias name confuses compilation
_ = erralias.ErrUnsupported
}
```
In this case, we will replace `"github.com/alibaba/opentelemetry-go-auto-instrumentation/pkg/api"` to `"errors"` and we have two `"errors"`, which finally leads to failure.

fix: import path may have alias name

---

.codeconv.yml
Makefile
main.go
test/build_test.go
test/infra.go
tool/build.go
tool/instrument/instrument.go
tool/instrument/optimize.go
tool/preprocess/fetch.go
tool/preprocess/match.go
tool/preprocess/pkgdep.go
tool/preprocess/preprocess.go
tool/preprocess/setup.go
tool/shared/config.go
tool/shared/flags.go
tool/shared/shared.go

related to #184 
RuleJsonFiles is the name of the rule file. It is used to tell instrument
tool where to find the instrument rules. Multiple rules are separated by
comma. e.g. -rule=rule1.json,rule2.json. By default, new rules are appended
to default rules, i.e. -rule=rule1.json,rule2.json is exactly equivalent to
-rule=default.json,rule1.json,rule2.json. But if you do want to replace the
default rules, you can add a "+" prefix to the rule file name, e.g.
-rule=+rule1.json,rule2.json. In this case, the default rules will be replaced
by rule1.json, and then rule2.json will be appended to the rules.

feat: coexist custom rules and default rules

---

tool/instrument/inst_func.go
tool/preprocess/setup.go
tool/util/util.go

Fix the following compilation error:
```
[instrument] 2024/11/15 13:54:28 Apply func rule github.com/go-kratos/kratos/v2/transport/grpc@[2.5.2,2.8.3)@DialInsecure {KratosDialInsecureOnEnter KratosDialInsecureOnExit}
[instrument] 2024/11/15 13:54:28 Apply func rule github.com/go-kratos/kratos/v2/transport/grpc@[2.5.2,2.8.3)@WithMiddleware {KratosGRPCWithMiddlewareOnEnter }
[instrument] 2024/11/15 13:54:29 Apply func rule github.com/go-kratos/kratos/v2/transport/grpc@[2.5.2,2.8.3)@NewServer {KratosNewGRPCServiceOnEnter }
[instrument] 2024/11/15 13:54:29 RunCmd: github.com/go-kratos/kratos/v2/transport/grpc (281.134908ms)
otel_rules/otel_setup_inst.go:27:8: http369 redeclared in this block
otel_rules/otel_setup_inst.go:13:8: other declaration of http369
otel_rules/otel_setup_inst.go:27:8: …
```

fix: make random string unique

---

README.md
docs/supported-libraries.md
go.mod
go.sum
pkg/data/default.json
pkg/rules/redigo/redigo_client_setup.go
pkg/rules/redigo/redigo_otel_conn.go
pkg/rules/redigo/redigo_otel_instrumenter.go
test/redigo/v1.9.0/go.mod
test/redigo/v1.9.0/test_do_commands.go
test/redigo/v1.9.0/test_executing_commands.go
test/redigo/v1.9.0/test_transaction.go
test/redigo/v1.9.0/test_unsupported_commands.go
test/redigo_tests.go

feat: support redigo v1.9.0+

---

pkg/rules/test/fmt7/hook.go
test/helloworld_test.go
tool/preprocess/match.go
tool/preprocess/preprocess.go
tool/preprocess/setup.go
tool/shared/ast.go

If api.CallContext has an alias, i.e. pkgapi.CallContext, while hooked package has alias name, the error happens.

fix: api.CallContext alias conflicts with hooked package

---

example/extension/nethttp/README.md
example/extension/nethttp/config.json
example/extension/sqlinject/README.md
pkg/data/default.json
pkg/rules/otel-sdk/otel_baggage_util.go
pkg/rules/otel-sdk/trace-context/otel_trace_context.go

The crash occurs because newproc1 is executed by the m0.g0 scheduling goroutine, which lacks racectx. However, contextPropagate inserted by -race forcibly adds a call to racefuncenter(), which expects racectx to be valid. Since m0.g0.racectx is 0, this leads to a crash.
One solution is to use the Go compiler's directive:
```
//go:norace
The //go:norace directive must be followed by a function declaration. It specifies that the function's memory accesses should be ignored by the race detector. This is most commonly used in low-level code invoked at times when it is unsafe to call into the race detector runtime.
```

fix: segfault on Takesnapshot when go build -race

---

pkg/data/default.json
tool/preprocess/match.go
tool/resource/ruledef.go
tool/util/log.go

Rule may instrument golang's standard libraries, which requires specific Go version in some rare cases, e.g.
```json
{
"ImportPath": "runtime",
"Function":"doInit",
"OnEnter": "reorderInitTasks(ts)",
"UseRaw": true,
"GoVersion": "[1.22.0,1.23.0)"
},
```

feat: allow rule specifying Golang version

---

test/build_test.go
tool/preprocess/preprocess.go
tool/util/util.go

`go build -o ./cmd ./cmd` may fail because of duplicated `./cmd`

fix: dont remove duplicated flags

---

tool/instrument/inst_func.go
tool/instrument/inst_struct.go
tool/instrument/instrument.go
tool/preprocess/match.go
tool/resource/bundle.go

use absolute path between Preprocess and Instrument phases, otherwise compilation fails due to different source path(e.g. `./src/to/client.go` and `/root/path/src/to/client.go`)

fix: use absolute path between Preprocess and Instrument phases

---

README.md
test/build_test.go
test/flags_test.go
test/infra.go
test/kitex/v0.5.1/go.mod
test/world_test.go
tool/cmd/main.go
tool/config/config.go
tool/errc/errcode.go
tool/instrument/inst_file.go
tool/instrument/inst_func.go
tool/instrument/inst_struct.go
tool/instrument/instrument.go
tool/instrument/optimize.go
tool/instrument/trampoline.go
tool/preprocess/fetch.go
tool/preprocess/match.go
tool/preprocess/pkgdep.go
tool/preprocess/preprocess.go
tool/preprocess/setup.go
tool/resource/bundle.go
tool/resource/resource.go
tool/resource/ruledef.go
tool/util/ast.go
tool/util/log.go
tool/util/shared.go
tool/util/util.go

related to #267 
standardize error message, something like bellow
```
Command    : ../../otel go build xxx
ErrorLog   : .otel-build/preprocess/debug.log
WorkDir    : /home/yyang/opentelemetry-go-auto-instrumentation/test/helloworld
GoMod      : /home/yyang/opentelemetry-go-auto-instrumentation/test/helloworld/go.mod
GoVersion  : go1.22.0
ToolVersion: 0.4.0_8a27e33
OS         : linux/amd64
Code       : 1014
Message    : exit status 1
Cause      : goroutine 1 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/alibaba/opentelemetry-go-auto-instrumentation/tool/errc.New(0x3f6, {0xc000013160, 0xd})
/home/yyang/opentelemetry-go-auto-instrumentation/tool/errc/errcode.go:57 +0x88
github.com/alibaba/opentelemetry-go-auto-instrumentation/tool/preprocess.run …
```

refine: standardized error message

---

tool/preprocess/fetch.go
tool/preprocess/match.go
tool/preprocess/preprocess.go
tool/resource/resource.go
tool/util/shared.go
tool/util/util.go

we should find modules.txt from `$PROJ_ROOT/vendor/modules.txt` instead of `$PWD/vendor/modulex.txt`

fix: find vendor/modules.txt from project root

---

example/extension/nethttp/README.md

The original compilation cmd `../../../otel -rule=config.json go build demo/net_http.go` is invalid and the arg `-rule` should be removed.

Fix cmd err in README of example/extension

---

pkg/rules/redigo/redigo_client_setup.go

I noticed that some functions of redigo instrumentation have never been used currently. Maybe they were used before but no longer in use now?

Remove deprecated functions

---

tool/preprocess/pkgdep.go
tool/preprocess/preprocess.go
tool/preprocess/setup.go

fix for #291 
I made mistakes on otel_rules initialization and corresponding removal, I need to revise it

fix: OtelRules initialized to wrong path

---

Makefile

When use `uname -m` in ARM Linux, the output is `aarch64` that cannot be recognized by Go, which means go build will fail with "unsupported GOOS/GOARCH pair linux/aarch64". Actually `aarch64` should be replaced with `arm64`.

Fix arch detection error in Makefile

---

test/helloworld_test.go
tool/instrument/inst_func.go
tool/preprocess/preprocess.go
tool/preprocess/setup.go

ignore vendor when explicitly required by using `go build -buildmode=mod` flag

fix: ignore vendor when explicitly required

---

test/helloworld_test.go
tool/preprocess/match.go

Related to #335 
Failed to find version of submodules

fix: failed to find version of submodules

---

test/errors_test.go
test/errorstest/auxiliary/helper.go
test/helloworld_test.go
tool/instrument/inst_func.go
tool/instrument/instrument.go
tool/instrument/optimize.go
tool/instrument/template.go
tool/instrument/trampoline.go
tool/preprocess/preprocess.go
tool/preprocess/setup.go
tool/util/ast.go

related to #247 
adjust line number via `//line` directive, something like this
```go
package main
//line <generated>
import _ "httpclient/otel_rules"
//line <generated>
import (
_ "go.opentelemetry.io/otel"
_ "go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc"
_ "go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp"
_ "go.opentelemetry.io/otel/exporters/otlp/otlptrace"
_ "go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
_ "go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"
_ "go.opentelemetry.io/otel/exporters/prometheus"
)
//line app4.go:17:1
import (
"context"
"net/http"
)
```
```go
func TestSkip2() (retVal0 int) {
//line <generated>
if callContext30412, skip30412 := OtelOnEnterTrampoline_TestSkip230412(); skip30412 { …
```

fix: adjust line number via //line directive

---

docs/how-to-add-a-new-rule.md
docs/rule_def.md
test/errorstest/auxiliary/helper.go
tool/util/ast.go

related to #349 
We prevent otel from crashing, but even after this patch is merged, matching receiver types with generics will still not be supported.

fix: unable to match target func with generic type receiver

---

pkg/inst-api/instrumenter/instrumenter.go
pkg/inst-api/instrumenter/instrumenter_test.go

Ref https://github.com/alibaba/opentelemetry-go-auto-instrumentation/issues/345
CC @NameHaibinZhang I've fixed this issue.
Before:
After:

fix span timestamp(duration) error with `StartAndEnd()`

---

README.md
docs/rule_def.md
go.mod
pkg/data/test_error.json
pkg/rules/test/error19/hook.go
test/errors_test.go
test/errorstest/all/match.go
test/errorstest/main.go
tool/instrument/inst_func.go
tool/instrument/instrument.go
tool/instrument/optimize.go
tool/instrument/trampoline.go
tool/util/ast.go

We can use regexp in the rules to match one or more target functions. Something like this
```json
{
"ImportPath": "errorstest/auxiliary",
"Function": ".*",
"OnEnter": "onEnterGeneric",
"Path": "github.com/alibaba/opentelemetry-go-auto-instrumentation/pkg/rules/test/error19"
}
```

feat: regexp based instrumentation point

---

tool/preprocess/match.go

Failed to parse the following lines
```
github.com/alibaba/opentelemetry-go-auto-instrumentation/test/verifier
```

fix: failed to parse vendor/modules.txt when replacement presents

---

docs/rule_def.md
pkg/data/default.json
pkg/data/test_error.json
pkg/data/test_nethttp.json
pkg/rules/test/error19/hook.go
test/errors_test.go
test/errorstest/all/match.go
tool/util/ast.go

related to #382 
Now `ReceiverType` field can be speficied via regular expression

feat: regexp-based ReceiverType

---

README.md
pkg/api/api.go
pkg/api/impl.go
pkg/data/test_error.json
pkg/rules/test/error19/hook.go
test/errors_test.go
tool/instrument/template.go
tool/instrument/trampoline.go

related to #390 
Implement new CallContext.{GetFuncName,GetPackageName} APIs

feat: new CallContext.{GetFuncName, GetPackageName} APIs

---

pkg/rules/runtime/reorder_init.go
tool/preprocess/pkgdep.go
tool/preprocess/preprocess.go
tool/preprocess/setup.go
tool/resource/resource.go

related to #388 
use otel_pkg/rules instead of otel_rules

chore: use otel_pkg/rules instead of otel_rules

---

tool/preprocess/preprocess.go

stop finding for `go.mod` if root is reached

fix: stop finding for go.mod if root is reached

---

pkg/rules/grpc/grpc_otel_instrumenter.go

This PR fixes an issue in grpcStatusCodeExtractor where it incorrectly judgment here should be 200 instead of 0.

Fix incorrect status code extraction in grpcStatusCodeExtractor

---

test/version/version.go

**Description:**
[`GetRandomVersion`](https://github.com/alibaba/opentelemetry-go-auto-instrumentation/blob/main/test/version/version.go#L410C1-L450C2) is optimized by adjusting the logic of obtaining random version numbers, filtering the appropriate version numbers first, and then randomly selecting the version numbers among the appropriate version numbers, and dealing with the version number format problem
**Relevant Issue:**
#458

chore: optimize get random version

---

pkg/inst-api-semconv/instrumenter/ai/ai_metrics.go
pkg/inst-api-semconv/instrumenter/ai/ai_metrics_test.go
pkg/otel_setup.go
pkg/rules/eino/eino_common_otel_instrumenter.go
pkg/rules/eino/eino_handler.go
pkg/rules/eino/eino_llm_otel_instrucmenter.go
test/eino/v0.3.51/test_chatmodel_metrics.go
test/eino/v0.3.51/test_invoke_chatmodel_metrics.go
test/eino/v0.3.51/test_stream_chatmodel_metrics.go
test/eino_tests.go
test/verifier/verifier.go

1. Support for OpenTelemetry GenAI metrics instrumentation 
- gen_ai.client.token.usage
- gen_ai.client.operation.duration
- gen_ai.server.time_to_first_token
2. Integrate these metrics into Eino instrumentation
> Note: The OpenTelemetry GenAI semantic conventions are currently in Stability: **development** and may change in future versions. See: https://opentelemetry.io/docs/specs/semconv/gen-ai/gen-ai-metrics/

feat: support genai metrics and add metrics in eino instrumentation

---

example/sqlinject/config.json

Fix #579 
Compilation error caused by incorrect `Path` field.
The test result after repair is as follows:
```
#./sqlinjectdemo
2025/09/28 14:22:03 sqlQueryOnEnter potential SQL injection detected
```

fix: Fix the error in building sql demo
